---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ym53tr5q/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /usr/local/bin/npm install --production --prefix $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/logs
    - /usr/local/bin/node $DEPLOYPATH/bot.js